twig:
    file_name_pattern: '*.twig'
    globals:
      app_public_url: '%env(APP_PUBLIC_URL)%'
      app_email: '%env(APP_EMAIL)%'
      annual_fee: 50
      access_badge_deposit: 10
      app_slogan: '%app.slogan%'

when@test:
    twig:
        strict_variables: true
