# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    admin.init.email: '%env(ADMIN_INIT_EMAIL)%'
    admin.init.password: '%env(ADMIN_INIT_PASSWORD)%'
    admin.init.lastname: '%env(ADMIN_INIT_LASTNAME)%'
    admin.init.firstname: '%env(ADMIN_INIT_FIRSTNAME)%'
    admin.init.gender: '%env(ADMIN_INIT_GENDER)%'
    admin.init.birthdate: '%env(ADMIN_INIT_BIRTHDATE)%'
    admin.init.phone: '%env(ADMIN_INIT_PHONE)%'
    admin.init.address: '%env(ADMIN_INIT_ADDRESS)%'
    admin.init.postalcode: '%env(ADMIN_INIT_POSTALCODE)%'
    admin.init.city: '%env(ADMIN_INIT_CITY)%'
    app.public.url: '%env(APP_PUBLIC_URL)%'
    app.email: '%env(APP_EMAIL)%'

    app.slogan: 'Rejoignez-nous pour vous dépasser et rester en forme !'
    membership.annual_fee: 50
    membership.access_badge_deposit: 10

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            int $annualFee: '%membership.annual_fee%'
            int $accessBadgeDeposit: '%membership.access_badge_deposit%'
            string $appSlogan: '%app.slogan%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

when@test:
    services:
        Symfony\Component\Security\Csrf\CsrfTokenManagerInterface:
            class: Symfony\Component\Security\Csrf\CsrfTokenManager

